import { Resend } from "resend";
import type { SylndrItem, Snapshot } from "./types.ts";
import { renderCard } from "./render.ts";

const FROM = "Sylndr Alert <onboarding@resend.dev>";

const EMAIL_CSS = `
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#fafafa;color:#111;margin:0;padding:24px}
.wrap{max-width:640px;margin:0 auto}
h1{font-size:20px;margin:0 0 12px}
.sub{color:#666;font-size:13px;margin:0 0 20px}
.card{background:#fff;border:1px solid #e6e6e6;border-radius:10px;overflow:hidden;margin-bottom:14px;display:block}
.thumb{display:block;width:100%;aspect-ratio:4/3;background:#000}
.thumb img{width:100%;height:100%;object-fit:cover;display:block}
.no-photo{width:100%;height:100%;display:flex;align-items:center;justify-content:center;color:#999;font-size:12px}
.body{padding:12px 14px}
.title{font-weight:600;color:#111;text-decoration:none;font-size:15px;display:block;margin-bottom:6px}
.price{font-size:18px;font-weight:700;color:#c95a00;margin-bottom:6px}
.badge{font-size:11px;background:#ffe7e7;color:#a33;padding:2px 7px;border-radius:999px;font-weight:600;margin-left:8px}
.meta{color:#666;font-size:13px}
.stamp{color:#999;font-size:11px;margin-top:4px}
footer{color:#999;font-size:11px;text-align:center;margin-top:24px}
`;

function itemsToSnapshots(items: SylndrItem[]): Snapshot[] {
  const now = new Date().toISOString();
  return items.map((i) => ({ ...i, firstSeen: now }));
}

export function renderDigest(items: SylndrItem[]): { subject: string; html: string } {
  const snaps = itemsToSnapshots(items);
  const cards = snaps.map((s) => renderCard(s, { compact: true })).join("\n");
  const subject =
    items.length === 1
      ? `New Sylndr listing: ${snaps[0].vehicle.carMake?.name ?? ""} ${snaps[0].vehicle.carModel?.name ?? ""}`.trim()
      : `${items.length} new Sylndr listings`;
  const html = `<!doctype html><html><head><meta charset="utf-8"><style>${EMAIL_CSS}</style></head><body><div class="wrap">
<h1>${items.length} new Sylndr ${items.length === 1 ? "listing" : "listings"}</h1>
<div class="sub">matched your filter &middot; ${new Date().toISOString().slice(0, 16).replace("T", " ")} UTC</div>
${cards}
<footer>auto-generated by sylndr-alert</footer>
</div></body></html>`;
  return { subject, html };
}

type SendKind = "new" | "seed" | "broken";

export async function sendEmail(
  kind: SendKind,
  payload: { items?: SylndrItem[]; message?: string; seedCount?: number },
): Promise<void> {
  const apiKey = process.env.RESEND_API_KEY;
  const to = process.env.EMAIL_TO;
  if (!apiKey || !to) {
    console.log(`[email] RESEND_API_KEY or EMAIL_TO not set — skipping ${kind} email (dry-run)`);
    return;
  }
  const resend = new Resend(apiKey);

  let subject: string;
  let html: string;
  if (kind === "new") {
    const digest = renderDigest(payload.items ?? []);
    subject = digest.subject;
    html = digest.html;
  } else if (kind === "seed") {
    subject = `Sylndr alerts seeded (${payload.seedCount ?? 0} listings)`;
    html = `<p>Sylndr alerts is now watching <strong>${payload.seedCount ?? 0}</strong> listings. Future runs will email when new ones appear.</p>`;
  } else {
    subject = `Sylndr alert: scraper broken`;
    html = `<p>The Sylndr scraper failed on 3 consecutive runs.</p><pre>${payload.message ?? ""}</pre>`;
  }

  const { error } = await resend.emails.send({ from: FROM, to, subject, html });
  if (error) {
    throw new Error(`Resend error: ${JSON.stringify(error)}`);
  }
  console.log(`[email] sent ${kind} to ${to}`);
}
